-- ============================================================================
-- NuraVision · 0001 · Esquema inicial
-- ============================================================================
-- Crea las cuatro tablas que el frontend ya consume. El contrato vive en
-- frontend/src/shared/types/supabase.ts: nombres y tipos de columna deben
-- coincidir con ese archivo, porque de ahi sale el tipado del cliente.
--
-- Pensado para un proyecto Supabase NUEVO y vacio. No usa "if not exists" a
-- proposito: si una tabla ya existe conviene que falle y no que siga de largo
-- dejando un esquema a medias.
--
-- Las politicas de seguridad van aparte, en 0002_rls.sql. Aplicar ese archivo
-- es obligatorio: sin el, las consultas del navegador vuelven vacias.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- servicios
-- ----------------------------------------------------------------------------
create table public.servicios (
  id               bigint generated by default as identity primary key,
  nombre           text    not null,
  -- Nullable a proposito: el frontend tolera una categoria ausente y cae en su
  -- valor por defecto (ver servicio.mapper.ts). Acepta tanto los ids del
  -- dominio ('unas', 'cabello', 'piel', 'diagnostico') como las variantes de
  -- presentacion ('Uñas', 'Estilismo', 'Estética'), normalizando tildes y
  -- mayusculas.
  categoria        text,
  descripcion      text,
  duracion_minutos integer not null,
  precio_base      numeric(10, 2) not null,
  activo           boolean not null default true,

  constraint servicios_duracion_positiva check (duracion_minutos > 0),
  constraint servicios_precio_no_negativo check (precio_base >= 0)
);

comment on table public.servicios is
  'Catalogo de servicios. Solo los activos se ofrecen para reservar.';
comment on column public.servicios.categoria is
  'Texto libre. El frontend lo normaliza contra el catalogo del dominio.';
comment on column public.servicios.activo is
  'false = fuera de catalogo. No aparece en el listado ni se puede reservar.';

-- El listado publico filtra por activo y ordena por nombre.
create index servicios_activos_idx
  on public.servicios (nombre)
  where activo;

-- ----------------------------------------------------------------------------
-- profesionales
-- ----------------------------------------------------------------------------
create table public.profesionales (
  id           bigint generated by default as identity primary key,
  nombre       text    not null,
  especialidad text    not null,
  -- Nullable: sin foto el frontend muestra las iniciales.
  avatar_url   text,
  activo       boolean not null default true,
  -- Presente en el proyecto original. El frontend no la lee: no esta en
  -- supabase.ts y las consultas que usan select('*') simplemente la ignoran.
  created_at   timestamptz not null default now()
);

comment on table public.profesionales is
  'Equipo del estudio. Solo los activos se ofrecen para reservar.';

create index profesionales_activos_idx
  on public.profesionales (nombre)
  where activo;

-- ----------------------------------------------------------------------------
-- profesional_servicios  (tabla puente)
-- ----------------------------------------------------------------------------
-- NOTA SOBRE LA INCONSISTENCIA CORREGIDA:
-- En el proyecto original esta columna era uuid mientras profesionales.id era
-- bigint. Los tipos no cruzaban y no habia clave foranea, asi que preguntar
-- "quien realiza este servicio" respondia:
--   invalid input syntax for type uuid: "1"
-- Aqui queda bigint, alineada con la tabla padre, y con FK declarada. La FK
-- ademas habilita los embedded select de PostgREST, por si mas adelante se
-- reemplazan las dos consultas del repositorio por un solo join.
create table public.profesional_servicios (
  profesional_id bigint not null
    references public.profesionales (id) on delete cascade,
  servicio_id    bigint not null
    references public.servicios (id) on delete cascade,

  primary key (profesional_id, servicio_id)
);

comment on table public.profesional_servicios is
  'Que profesional realiza que servicio. Relacion muchos a muchos.';

-- La PK ya cubre las busquedas que empiezan por profesional_id. Este indice es
-- para el camino inverso, que es el que mas se usa: desde el detalle de un
-- servicio se pregunta quien lo realiza (where servicio_id = ...).
create index profesional_servicios_servicio_idx
  on public.profesional_servicios (servicio_id);

-- ----------------------------------------------------------------------------
-- disponibilidad
-- ----------------------------------------------------------------------------
-- CONVENCION DE dia_semana: 0 = domingo … 6 = sabado.
-- Es el mismo indice que Date.getDay() en JavaScript, y es lo que asume
-- DIA_SEMANA_BASE en
-- frontend/src/modules/profesionales/infrastructure/disponibilidad.mapper.ts.
-- Si se cambia aqui, hay que cambiarlo alli: quedarian los horarios corridos.
create table public.disponibilidad (
  id             bigint generated by default as identity primary key,
  profesional_id bigint  not null
    references public.profesionales (id) on delete cascade,
  dia_semana     integer not null,
  hora_inicio    time    not null,
  hora_fin       time    not null,

  constraint disponibilidad_dia_valido
    check (dia_semana between 0 and 6),
  constraint disponibilidad_rango_valido
    check (hora_fin > hora_inicio),
  -- Un profesional no puede tener dos bloques que arranquen a la misma hora
  -- el mismo dia.
  constraint disponibilidad_sin_duplicados
    unique (profesional_id, dia_semana, hora_inicio)
);

comment on table public.disponibilidad is
  'Horario semanal. Un dia puede tener varios bloques; el hueco entre dos '
  'bloques consecutivos se interpreta como colacion.';
comment on column public.disponibilidad.dia_semana is
  '0 = domingo … 6 = sabado (mismo indice que Date.getDay en JavaScript).';

-- El horario siempre se pide por profesional, ordenado por dia y hora.
create index disponibilidad_profesional_idx
  on public.disponibilidad (profesional_id, dia_semana, hora_inicio);
