-- ============================================================================
-- NuraVision · 0003 · Reservas
-- ============================================================================
-- Crea la tabla `reservas` desde cero, alineada con lo que ya esta en develop:
--
--   · "Permite reservar sin tener cuenta": sin sesion, el nombre, el correo y
--     el telefono son el UNICO vinculo con la reserva.
--   · profesionales.id y servicios.id son bigint, asi que las claves foraneas
--     tambien lo son. En el proyecto original profesional_id era uuid y no
--     cruzaba con su tabla padre: no habia valor valido que guardar.
--
-- ----------------------------------------------------------------------------
-- ⚠  ATENCION: empieza con un DROP. Si la tabla ya existe, se pierde su
--    contenido. Es lo que permite re-ejecutar la migracion y que un proyecto
--    nuevo quede igual que uno existente, pero no la apliques sobre reservas
--    que te importen sin respaldarlas antes.
-- ----------------------------------------------------------------------------
drop table if exists public.reservas cascade;

-- ----------------------------------------------------------------------------
-- Estado de la reserva
-- ----------------------------------------------------------------------------
-- El tipo sobrevive al DROP de la tabla, asi que se crea solo si falta. No se
-- elimina y se recrea a proposito: un drop cascade del tipo se llevaria por
-- delante cualquier otra columna que lo use.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'estado_reserva') then
    create type public.estado_reserva as enum (
      'pendiente',
      'confirmada',
      'completada',
      'cancelada'
    );
  end if;
end
$$;

-- ----------------------------------------------------------------------------
-- reservas
-- ----------------------------------------------------------------------------
create table public.reservas (
  id             bigint generated by default as identity primary key,

  -- bigint explicito, igual que las columnas a las que apuntan.
  servicio_id    bigint not null
    references public.servicios (id),
  profesional_id bigint not null
    references public.profesionales (id),

  fecha          date not null,
  hora_inicio    time not null,
  -- Se guarda en vez de derivarse de la duracion del servicio: si esa duracion
  -- cambia mañana, las reservas ya tomadas conservan el bloque real.
  hora_fin       time not null,

  -- Contacto de quien reserva. Con sesion se rellena desde la cuenta; sin
  -- sesion es el unico vinculo con la reserva.
  cliente_nombre   text not null,
  cliente_email    text not null,
  cliente_telefono text,

  -- Perfil asociado cuando la reserva la hizo alguien con cuenta.
  -- Sin clave foranea a proposito: `perfiles` no forma parte de estas
  -- migraciones, y declararla haria fallar la instalacion en un proyecto
  -- nuevo. Cuando `perfiles` se versione, conviene agregarla.
  cliente_id     uuid,

  -- Lo que identifica la reserva para quien no tiene historial que consultar.
  codigo         text not null unique,

  estado         public.estado_reserva not null default 'pendiente',

  creada_en      timestamptz not null default now(),

  constraint reservas_rango_valido
    check (hora_fin > hora_inicio),
  constraint reservas_email_presente
    check (nullif(btrim(cliente_email), '') is not null),
  constraint reservas_nombre_presente
    check (nullif(btrim(cliente_nombre), '') is not null)
);

comment on table public.reservas is
  'Horas reservadas. Admite reservas con y sin cuenta.';
comment on column public.reservas.cliente_id is
  'Perfil asociado, o NULL si la reserva se hizo sin cuenta.';
comment on column public.reservas.codigo is
  'Codigo visible. Es como identifica su hora quien reservo sin cuenta.';
comment on column public.reservas.hora_fin is
  'Se calcula con la duracion del servicio al reservar y se congela aqui.';

-- ----------------------------------------------------------------------------
-- Indices
-- ----------------------------------------------------------------------------
-- La agenda de un profesional se consulta por dia y hora.
create index reservas_agenda_idx
  on public.reservas (profesional_id, fecha, hora_inicio);

-- Historial de quien tiene cuenta.
create index reservas_cliente_idx
  on public.reservas (cliente_id)
  where cliente_id is not null;

-- Busqueda del invitado por su correo.
create index reservas_email_idx
  on public.reservas (lower(cliente_email));

-- `codigo` ya tiene indice unico por la restriccion UNIQUE de la columna.

-- ----------------------------------------------------------------------------
-- RLS: solo INSERT para el rol anonimo
-- ----------------------------------------------------------------------------
-- Reservar sin cuenta obliga a que un visitante sin sesion pueda crear filas.
-- El costo es inherente a esa decision de producto: cualquiera con la anon key
-- puede insertar. Se acota lo que se puede:
--
--   · `estado` forzado a 'pendiente'. Nadie se auto-confirma una hora;
--     confirmar queda del lado del equipo, con otro rol.
--   · Nombre y correo obligatorios, para que no se creen filas huerfanas.
--   · NO se otorga SELECT. Sin autenticacion no hay forma de acotar la lectura
--     a "mis reservas", y abrirla expondria el contacto de todos los clientes.
--
-- CONSECUENCIA: desde el navegador la tabla es de SOLO ESCRITURA. Ni siquiera
-- se puede leer de vuelta la fila recien creada (PostgREST necesita SELECT
-- para devolverla), asi que la app no conoce el id generado y usa su `codigo`.
-- Cuando exista Supabase Auth, lo correcto es sumar un SELECT acotado a
-- cliente_id = auth.uid().
alter table public.reservas enable row level security;

create policy "insercion publica de reservas"
  on public.reservas
  for insert
  to anon, authenticated
  with check (
    estado = 'pendiente'
    and nullif(btrim(cliente_nombre), '') is not null
    and nullif(btrim(cliente_email), '') is not null
  );

grant usage on schema public to anon, authenticated;
grant insert on public.reservas to anon, authenticated;

-- Sin SELECT, UPDATE ni DELETE para anon. La columna `id` es identity, que no
-- requiere permisos sobre secuencias.

notify pgrst, 'reload schema';
